# Generated by Django 5.0.6 on 2024-06-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reposteria', '0002_coctel_imagen_pan_pascua_imagen_torta_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=15)),
                ('telefono', models.IntegerField()),
                ('correo', models.EmailField(max_length=254)),
                ('tipo', models.IntegerField(choices=[(0, 'Reposteria'), (1, 'Eventos'), (2, 'Pan de Pascua')])),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
